name: First workflow #name of workflow that appears on  actions tab

on: push  #it is event  that specifies to trigger this workflow

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: sample checkout step
    - run: echo "this is my first workflow"
